apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: synergychat-web
  name: synergychat-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: synergychat-web
  template:
    metadata:
      labels:
        app: synergychat-web
    spec:
      containers:
        - image: bootdotdev/synergychat-web:latest
          name: synergychat-web
          resources: {}
          env:
            - name: WEB_PORT
              valueFrom:
                configMapKeyRef:
                  name: synergychat-api-configmap
                  key: WEB_PORT
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: synergychat-api-configmap
                  key: API_URL